import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/Components/Nav";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "huntingCoder-A Blog by a Coder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        
        <body className={inter.className}>
          <Nav />
          {children}
          <Footer />
          
        </body>
      </html>
    </>
  );
}
